### ISSUE TITLE
Please resize and center hero image

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/French#2]
Hey @ZMcGroarty can you center and resize the hero? I can if you can't get to it, thanks!

**Comment by ZMcGroarty** [comment]
![hero_french-min](https://user-images.githubusercontent.com/15017242/37609732-4ad5ca0e-2b74-11e8-8e40-53a5c80f89f0.png)

**Comment by CVE82** [comment]
You're the bomb thank you!
